GET http://127.0.0.1/api/users/{{username}}/history
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-Auth-Token: {{xAuthToken}}

####

GET http://127.0.0.1/api/users/{{username}}/history?search=Matrix
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-Auth-Token: {{xAuthToken}}

####

GET http://127.0.0.1/api/users/{{username}}/history?limit=5
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-Auth-Token: {{xAuthToken}}

####
