GET http://127.0.0.1/api/users/{{username}}/history/movies?search=Matrix&limit=10
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-Movary-Token: {{xMovaryToken}}

####

PUT http://127.0.0.1/api/users/{{username}}/history/movies
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-Movary-Token: {{xMovaryToken}}

[{"movaryId" : 1, "watchedAt" : "2011-05-06", "plays" :  1, "comment" :  "comment"}]

####

POST http://127.0.0.1/api/users/{{username}}/history/movies
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-Movary-Token: {{xMovaryToken}}

[{"movaryId" : 1, "watchedAt" : "2011-05-06"}]

####

DELETE http://127.0.0.1/api/users/{{username}}/history/movies
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-Movary-Token: {{xMovaryToken}}

[{"movaryId" : 1, "watchedAt" : "2011-05-06"}]

####
