GET http://127.0.0.1/api/ussers/{{username}}/watchlist
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-Auth-Token: {{xAuthToken}}

####

GET http://127.0.0.1/api/users/{{username}}/watchlist?limit=5
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-Auth-Token: {{xAuthToken}}

####
