## HistoryApi

### Delete movie watch dates from user history
# @name usersUsernameHistoryMoviesDelete
DELETE http://localhost/users/{{username}}/history/movies
Content-Type: application/json

### Get played movies with watch dates of user
# @name usersUsernameHistoryMoviesGet
GET http://localhost/users/{{username}}/history/movies

### Add movie play with watch date set to user
# @name usersUsernameHistoryMoviesPost
POST http://localhost/users/{{username}}/history/movies
Content-Type: application/json

### Replace movie play with watch date set for user
# @name usersUsernameHistoryMoviesPut
PUT http://localhost/users/{{username}}/history/movies
Content-Type: application/json
