## WatchlistApi

### Delete movie from watchlist of user
# @name usersUsernameWatchlistMoviesDelete
DELETE http://localhost/users/{{username}}/watchlist/movies
Content-Type: application/json

### Get movies in watchlist of user
# @name usersUsernameWatchlistMoviesGet
GET http://localhost/users/{{username}}/watchlist/movies

### Add movie to watchlist of user
# @name usersUsernameWatchlistMoviesPost
POST http://localhost/users/{{username}}/watchlist/movies
Content-Type: application/json
