## WebhooksApi

### 
# @name webhookEmbyUuidPost
POST http://localhost/webhook/emby/{{uuid}}

### 
# @name webhookJellyfinUuidPost
POST http://localhost/webhook/jellyfin/{{uuid}}

### 
# @name webhookPlexUuidPost
POST http://localhost/webhook/plex/{{uuid}}
