POST http://127.0.0.1/jellyfin/a7a0b0ab-41aa-4641-a199-b784f88886f8
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

{
  "ServerId": "e7f44197df844fc4a503f7366b746adc",
  "ServerName": "leepe-pc",
  "ServerVersion": "10.8.8",
  "ServerUrl": "",
  "NotificationType": "PlaybackStop",
  "Timestamp":    "2023-01-04T07:36:12.8535895+01:00",
  "UtcTimestamp": "2023-01-04T06:36:12.853591Z",
  "Name": "The Menu",
  "Overview": "A couple travels to a coastal island to eat at an exclusive restaurant where the chef has prepared a lavish menu, with some shocking surprises.",
  "Tagline": "Painstakingly prepared. Brilliantly executed.",
  "ItemId": "9871a124b152901edc3aafa0f374d14e",
  "ItemType": "Movie",
  "RunTimeTicks": 64274239488,
  "RunTime": "01:47:07",
  "Year": 2022,
  "Provider_tmdb": "593643",
  "Provider_imdb": "tt9764362",
  "Video_0_Title": "4K HEVC HDR",
  "Video_0_Type": "Video",
  "Video_0_Codec": "hevc",
  "Video_0_Profile": "Main 10",
  "Video_0_Level": 150,
  "Video_0_Height": 1634,
  "Video_0_Width": 3840,
  "Video_0_AspectRatio": "2.35:1",
  "Video_0_Interlaced": false,
  "Video_0_FrameRate": 23.976025,
  "Video_0_VideoRange": "HDR",
  "Video_0_ColorSpace": "bt2020nc",
  "Video_0_ColorTransfer": "smpte2084",
  "Video_0_ColorPrimaries": "bt2020",
  "Video_0_PixelFormat": "yuv420p10le",
  "Video_0_RefFrames": 1,
  "Audio_0_Title": "English - Dolby Digital\u002B - 5.1 - Default",
  "Audio_0_Type": "Audio",
  "Audio_0_Language": "eng",
  "Audio_0_Codec": "eac3",
  "Audio_0_Channels": 6,
  "Audio_0_Bitrate": 768000,
  "Audio_0_SampleRate": 48000,
  "Audio_0_Default": true,
  "Subtitle_0_Title": "English - SUBRIP",
  "Subtitle_0_Type": "Subtitle",
  "Subtitle_0_Language": "eng",
  "Subtitle_0_Codec": "subrip",
  "Subtitle_0_Default": false,
  "Subtitle_0_Forced": false,
  "Subtitle_0_External": false,
  "Subtitle_1_Title": "English - SUBRIP",
  "Subtitle_1_Type": "Subtitle",
  "Subtitle_1_Language": "eng",
  "Subtitle_1_Codec": "subrip",
  "Subtitle_1_Default": false,
  "Subtitle_1_Forced": false,
  "Subtitle_1_External": false,
  "Subtitle_2_Title": "French Canadian - SUBRIP",
  "Subtitle_2_Type": "Subtitle",
  "Subtitle_2_Language": "fre",
  "Subtitle_2_Codec": "subrip",
  "Subtitle_2_Default": false,
  "Subtitle_2_Forced": false,
  "Subtitle_2_External": false,
  "Subtitle_3_Title": "Latin America Spanish - SUBRIP",
  "Subtitle_3_Type": "Subtitle",
  "Subtitle_3_Language": "spa",
  "Subtitle_3_Codec": "subrip",
  "Subtitle_3_Default": false,
  "Subtitle_3_Forced": false,
  "Subtitle_3_External": false,
  "PlaybackPositionTicks": 4549227060,
  "PlaybackPosition": "00:07:34",
  "MediaSourceId": "9871a124b152901edc3aafa0f374d14e",
  "IsPaused": false,
  "IsAutomated": false,
  "DeviceId": "TW96aWxsYS81LjAgKFgxMTsgVWJ1bnR1OyBMaW51eCB4ODZfNjQ7IHJ2OjEwOC4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzEwOC4wfDE2NzIyNTMwMjU5MDU1",
  "DeviceName": "Firefox",
  "ClientName": "Jellyfin Web",
  "PlayedToCompletion": true,
  "NotificationUsername": "jellyfin",
  "UserId": "50e1109a03fd4e13a3a5dd9bb27e08ec"
}

