<?php declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class UpdateCountryTables extends AbstractMigration
{
    public function down(): void
    {
        $this->execute('DROP TABLE IF EXISTS `country`');

        $this->execute(
            <<<SQL
            CREATE TABLE `cache_tmdb_countries` (
                `iso_3166_1` CHAR(2) NOT NULL,
                `english_name` VARCHAR(255) NOT NULL,
                PRIMARY KEY (`iso_3166_1`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
            SQL
        );
    }

    public function up(): void
    {
        $this->execute('DROP TABLE IF EXISTS `cache_tmdb_countries`');

        $this->execute(
            <<<SQL
            CREATE TABLE `country` (
                `iso_3166_1` CHAR(2) NOT NULL,
                `english_name` VARCHAR(255) NOT NULL,
                `updated_at` DATETIME DEFAULT NULL ON UPDATE NOW(),
                `created_at` DATETIME NOT NULL DEFAULT NOW(),
                PRIMARY KEY (`iso_3166_1`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
            SQL
        );

        $this->execute(
            <<<SQL
            INSERT INTO country (iso_3166_1, english_name)
            VALUES
                ('AD', 'Andorra'),
                ('AE', 'United Arab Emirates'),
                ('AF', 'Afghanistan'),
                ('AG', 'Antigua and Barbuda'),
                ('AI', 'Anguilla'),
                ('AL', 'Albania'),
                ('AM', 'Armenia'),
                ('AN', 'Netherlands Antilles'),
                ('AO', 'Angola'),
                ('AQ', 'Antarctica'),
                ('AR', 'Argentina'),
                ('AS', 'American Samoa'),
                ('AT', 'Austria'),
                ('AU', 'Australia'),
                ('AW', 'Aruba'),
                ('AZ', 'Azerbaijan'),
                ('BA', 'Bosnia and Herzegovina'),
                ('BB', 'Barbados'),
                ('BD', 'Bangladesh'),
                ('BE', 'Belgium'),
                ('BF', 'Burkina Faso'),
                ('BG', 'Bulgaria'),
                ('BH', 'Bahrain'),
                ('BI', 'Burundi'),
                ('BJ', 'Benin'),
                ('BM', 'Bermuda'),
                ('BN', 'Brunei Darussalam'),
                ('BO', 'Bolivia'),
                ('BR', 'Brazil'),
                ('BS', 'Bahamas'),
                ('BT', 'Bhutan'),
                ('BU', 'Burma'),
                ('BV', 'Bouvet Island'),
                ('BW', 'Botswana'),
                ('BY', 'Belarus'),
                ('BZ', 'Belize'),
                ('CA', 'Canada'),
                ('CC', 'Cocos  Islands'),
                ('CD', 'Congo'),
                ('CF', 'Central African Republic'),
                ('CG', 'Congo'),
                ('CH', 'Switzerland'),
                ('CI', 'Cote D\'Ivoire'),
                ('CK'  ,'Cook Islands'),
                ('CL', 'Chile'),
                ('CM', 'Cameroon'),
                ('CN', 'China'),
                ('CO', 'Colombia'),
                ('CR', 'Costa Rica'),
                ('CS', 'Serbia and Montenegro'),
                ('CU', 'Cuba'),
                ('CV', 'Cape Verde'),
                ('CX', 'Christmas Island'),
                ('CY', 'Cyprus'),
                ('CZ', 'Czech Republic'),
                ('DE', 'Germany'),
                ('DJ', 'Djibouti'),
                ('DK', 'Denmark'),
                ('DM', 'Dominica'),
                ('DO', 'Dominican Republic'),
                ('DZ', 'Algeria'),
                ('EC', 'Ecuador'),
                ('EE', 'Estonia'),
                ('EG', 'Egypt'),
                ('EH', 'Western Sahara'),
                ('ER', 'Eritrea'),
                ('ES', 'Spain'),
                ('ET', 'Ethiopia'),
                ('FI', 'Finland'),
                ('FJ', 'Fiji'),
                ('FK', 'Falkland Islands'),
                ('FM', 'Micronesia'),
                ('FO', 'Faeroe Islands'),
                ('FR', 'France'),
                ('GA', 'Gabon'),
                ('GB', 'United Kingdom'),
                ('GD', 'Grenada'),
                ('GE', 'Georgia'),
                ('GF', 'French Guiana'),
                ('GH', 'Ghana'),
                ('GI', 'Gibraltar'),
                ('GL', 'Greenland'),
                ('GM', 'Gambia'),
                ('GN', 'Guinea'),
                ('GP', 'Guadaloupe'),
                ('GQ', 'Equatorial Guinea'),
                ('GR', 'Greece'),
                ('GS', 'South Georgia and the South Sandwich Islands'),
                ('GT', 'Guatemala'),
                ('GU', 'Guam'),
                ('GW', 'Guinea-Bissau'),
                ('GY', 'Guyana'),
                ('HK', 'Hong Kong'),
                ('HM', 'Heard and McDonald Islands'),
                ('HN', 'Honduras'),
                ('HR', 'Croatia'),
                ('HT', 'Haiti'),
                ('HU', 'Hungary'),
                ('ID', 'Indonesia'),
                ('IE', 'Ireland'),
                ('IL', 'Israel'),
                ('IN', 'India'),
                ('IO', 'British Indian Ocean Territory'),
                ('IQ', 'Iraq'),
                ('IR', 'Iran'),
                ('IS', 'Iceland'),
                ('IT', 'Italy'),
                ('JM', 'Jamaica'),
                ('JO', 'Jordan'),
                ('JP', 'Japan'),
                ('KE', 'Kenya'),
                ('KG', 'Kyrgyz Republic'),
                ('KH', 'Cambodia'),
                ('KI', 'Kiribati'),
                ('KM', 'Comoros'),
                ('KN', 'St. Kitts and Nevis'),
                ('KP', 'North Korea'),
                ('KR', 'South Korea'),
                ('KW', 'Kuwait'),
                ('KY', 'Cayman Islands'),
                ('KZ', 'Kazakhstan'),
                ('LA', 'Lao People\'s Democratic Republic'),
                ('LB', 'Lebanon'),
                ('LC', 'St. Lucia'),
                ('LI', 'Liechtenstein'),
                ('LK', 'Sri Lanka'),
                ('LR', 'Liberia'),
                ('LS', 'Lesotho'),
                ('LT', 'Lithuania'),
                ('LU', 'Luxembourg'),
                ('LV', 'Latvia'),
                ('LY', 'Libyan Arab Jamahiriya'),
                ('MA', 'Morocco'),
                ('MC', 'Monaco'),
                ('MD', 'Moldova'),
                ('ME', 'Montenegro'),
                ('MG', 'Madagascar'),
                ('MH', 'Marshall Islands'),
                ('MK', 'Macedonia'),
                ('ML', 'Mali'),
                ('MM', 'Myanmar'),
                ('MN', 'Mongolia'),
                ('MO', 'Macao'),
                ('MP', 'Northern Mariana Islands'),
                ('MQ', 'Martinique'),
                ('MR', 'Mauritania'),
                ('MS', 'Montserrat'),
                ('MT', 'Malta'),
                ('MU', 'Mauritius'),
                ('MV', 'Maldives'),
                ('MW', 'Malawi'),
                ('MX', 'Mexico'),
                ('MY', 'Malaysia'),
                ('MZ', 'Mozambique'),
                ('NA', 'Namibia'),
                ('NC', 'New Caledonia'),
                ('NE', 'Niger'),
                ('NF', 'Norfolk Island'),
                ('NG', 'Nigeria'),
                ('NI', 'Nicaragua'),
                ('NL', 'Netherlands'),
                ('NO', 'Norway'),
                ('NP', 'Nepal'),
                ('NR', 'Nauru'),
                ('NU', 'Niue'),
                ('NZ', 'New Zealand'),
                ('OM', 'Oman'),
                ('PA', 'Panama'),
                ('PE', 'Peru'),
                ('PF', 'French Polynesia'),
                ('PG', 'Papua New Guinea'),
                ('PH', 'Philippines'),
                ('PK', 'Pakistan'),
                ('PL', 'Poland'),
                ('PM', 'St. Pierre and Miquelon'),
                ('PN', 'Pitcairn Island'),
                ('PR', 'Puerto Rico'),
                ('PS', 'Palestinian Territory'),
                ('PT', 'Portugal'),
                ('PW', 'Palau'),
                ('PY', 'Paraguay'),
                ('QA', 'Qatar'),
                ('RE', 'Reunion'),
                ('RO', 'Romania'),
                ('RS', 'Serbia'),
                ('RU', 'Russia'),
                ('RW', 'Rwanda'),
                ('SA', 'Saudi Arabia'),
                ('SB', 'Solomon Islands'),
                ('SC', 'Seychelles'),
                ('SD', 'Sudan'),
                ('SE', 'Sweden'),
                ('SG', 'Singapore'),
                ('SH', 'St. Helena'),
                ('SI', 'Slovenia'),
                ('SJ', 'Svalbard & Jan Mayen Islands'),
                ('SK', 'Slovakia'),
                ('SL', 'Sierra Leone'),
                ('SM', 'San Marino'),
                ('SN', 'Senegal'),
                ('SO', 'Somalia'),
                ('SR', 'Suriname'),
                ('SS', 'South Sudan'),
                ('ST', 'Sao Tome and Principe'),
                ('SU', 'Soviet Union'),
                ('SV', 'El Salvador'),
                ('SY', 'Syrian Arab Republic'),
                ('SZ', 'Swaziland'),
                ('TC', 'Turks and Caicos Islands'),
                ('TD', 'Chad'),
                ('TF', 'French Southern Territories'),
                ('TG', 'Togo'),
                ('TH', 'Thailand'),
                ('TJ', 'Tajikistan'),
                ('TK', 'Tokelau'),
                ('TL', 'Timor-Leste'),
                ('TM', 'Turkmenistan'),
                ('TN', 'Tunisia'),
                ('TO', 'Tonga'),
                ('TP', 'East Timor'),
                ('TR', 'Turkey'),
                ('TT', 'Trinidad and Tobago'),
                ('TV', 'Tuvalu'),
                ('TW', 'Taiwan'),
                ('TZ', 'Tanzania'),
                ('UA', 'Ukraine'),
                ('UG', 'Uganda'),
                ('UM', 'United States Minor Outlying Islands'),
                ('US', 'United States of America'),
                ('UY', 'Uruguay'),
                ('UZ', 'Uzbekistan'),
                ('VA', 'Holy See'),
                ('VC', 'St. Vincent and the Grenadines'),
                ('VE', 'Venezuela'),
                ('VG', 'British Virgin Islands'),
                ('VI', 'US Virgin Islands'),
                ('VN', 'Vietnam'),
                ('VU', 'Vanuatu'),
                ('WF', 'Wallis and Futuna Islands'),
                ('WS', 'Samoa'),
                ('XC', 'Czechoslovakia'),
                ('XG', 'East Germany'),
                ('XI', 'Northern Ireland'),
                ('XK', 'Kosovo'),
                ('YE', 'Yemen'),
                ('YT', 'Mayotte'),
                ('YU', 'Yugoslavia'),
                ('ZA', 'South Africa'),
                ('ZM', 'Zambia'),
                ('ZR', 'Zaire'),
                ('ZW', 'Zimbabwe')
            SQL
        );
    }
}