name: Deploy mkdocs to https://docs.movary.org

on:
  release:
    types: [published]
    paths:
      - docs/**
      - mkdocs.yml

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DOCS_SSH_HOST }}
          username: ${{ secrets.DOCS_SSH_USER }}
          key: ${{ secrets.DOCS_SSH_KEY }}
          source: "mkdocs.yml,docs/*"
          target: ${{ secrets.DOCS_DEPLOYMENT_DIRECTORY }}
          rm: true
      - uses: actions/checkout@v4
      - name: restart docker containers
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DOCS_SSH_HOST }}
          username: ${{ secrets.DOCS_SSH_USER }}
          key: ${{ secrets.DOCS_SSH_KEY }}
          script: cd ${{ secrets.DOCS_DEPLOYMENT_DIRECTORY }}/.. && docker compose restart
